---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: '0 8 * * *' # Every day at 08:00
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions: {}

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest

    permissions:
      contents: write # only for delete-branch option
      issues: write # label and close stale issues
      pull-requests: write # label and close stale PRs
    steps:
      - uses: ivuorinen/actions/stale@7ad79268dba5d86a7ec07512519b9d985c5ef208 # v2026.09.08
