---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync Labels

on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/labels.yml'
      - '.github/workflows/sync-labels.yml'
  schedule:
    - cron: '34 5 * * *' # Run every day at 05:34 AM UTC
  workflow_call:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  labels:
    name: ♻️ Sync Labels
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      issues: write

    steps:
      - name: ⤵️ Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ⤵️ Sync Latest Labels Definitions
        uses: ivuorinen/actions/sync-labels@e3b436adb3d9871b9cc27e19d13ba7f50cbac62e # 25.8.18
