---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync Labels

on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/labels.yml'
      - '.github/workflows/sync-labels.yml'
  schedule:
    - cron: '34 5 * * *' # Run every day at 05:34 AM UTC
  workflow_call:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  labels:
    name: ♻️ Sync Labels
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      issues: write

    steps:
      - name: ⤵️ Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ⤵️ Sync Latest Labels Definitions
        uses: ivuorinen/actions/sync-labels@fa0232d3c4ba16d087b606296435354a69c01756 # 25.8.11
